# Generated by Django 6.0.7 on 2026-07-23 13:49

from django.db import migrations

def populate_data(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Group = apps.get_model('accounts', 'Group')
    
    departments = [
        'Computer Science & Engineering',
        'Electrical & Electronics Engineering',
        'Mechanical Engineering',
        'Civil Engineering',
        'Business Administration',
        'Humanities & Sciences',
    ]
    for dept in departments:
        Department.objects.get_or_create(name=dept)
        
    groups = [
        'Undergraduates',
        'Postgraduates',
        'PhD Scholars',
        'Faculty Members',
        'Research Groups',
    ]
    for grp in groups:
        Group.objects.get_or_create(name=grp)

def rollback_data(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Group = apps.get_model('accounts', 'Group')
    Department.objects.all().delete()
    Group.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data, rollback_data),
    ]
